<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>hvorB Main Page</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!--    <link type="text/css" rel="stylesheet" href="/public/css/normalize.css"/>-->
    <link type="text/css" rel="stylesheet" href="./css/style.css"/>
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.typekit.net/xmc2tza.css">

</head>
<body>
    <div class="container">
        <h1>hvorB.</h1>
        <h2>Find User</h2>
        <div class="findUserContainer">
            <form method="post" name="findUserForm">
                <input type="text" name="firstName" id="input-first-name" placeholder="First name..." class="col-5 formInputs">
                <input type="text" name="surname" id="input-surname" placeholder="Surname..." class="col-5 formInputs">
                <input type="text" name="company" id="input-company" placeholder="Known company..." class="col-5 formInputs">
                <input type="email" name="email" id="input-email" placeholder="Known email..." class="col-5 formInputs">
                <button type="submit" value="submit" id="findUser-submit" class="btn btn-success">Find User</button>
            </form>
        </div>


    </div>

</body>
</html>
